### ISSUE TITLE
Create landing page EJS template 

### ISSUE THREAD

**Issue by teknoboten** [jtoguri/decision_wizard#2]

**Comment by teknoboten** [comment]
![](https://cdn.discordapp.com/attachments/967109659771170897/968607098734800987/unknown.png)

**Comment by jeffbushdesign** [comment]
Display the 'create new poll' form
--> DONE
- I added a title 'Create New Poll' over the form (not 100% sure what you meant here)

Alter the form based on cookie / !cookie
--> DONE

Allow users to add additional choices / descriptions
--> PARTIALLY DONE.
- could be because other areas of the page are incomplete but the (+) Add Option button doesn't work yet
- I need to figure out how to dynamically increment the option name input field since this needs to be unique and it's required for each option
